
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28.3/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: CYGWIN - 3.6.4-1.x86_64 - x86_64
...
